### PR TITLE
Fix missing Yatabar on the low level characters

### PR DESCRIPTION
**Pull request by keolwyn**
Commit fixed issue #2

### CODE REVIEW

**Comment by KaybeHud** [comment]
Just thinking about it, if you remove only the break, then the check is useless, isnt it?
I have put the rest of the code in an else block, maybe you can try this

**Comment by keolwyn** [comment]
To be honest, I thought you've added it just for logging purposes.

**Comment by KaybeHud** [comment]
:D not only
After checking if the element (e.g AIR) is not available, Yatabar.availableTotems[element] should no be  created with that element.
Thats why I put the break in it.
Maybe you could test it?

**Comment by keolwyn** [comment]
Clean install

Screenshot_4

Screenshot_6

**Comment by keolwyn** [comment]
On line 190 inside the function `AddOptionsForTotems()` in `Config.lua`

```lua
for idx, spell in pairs(self.availableTotems[element]) do
    if idx ~= "count" then
        buttonGrp = Yatabar:AddOptionsForTotem(idx, element, spell.id, spell.name)
        if buttonGrp ~= nil then
            table.insert(self.options.args.totems.args[element].args, buttonGrp)
        end
    end
end
```
`self.availableTotems[element]` would be `nil` for AIR element. I just wrapped the code block above in nil check and it was fixed.

**Review by KaybeHud — APPROVED** [review]

**Comment by KaybeHud** [comment]
Thats it. I have put it all together, should be work now.
Thank you very much

**Review by KaybeHud — COMMENTED** [review]
-

**Pull request closed without merging**
